version: '3'

volumes:
  pg_data:
  static:
  media:
  redoc:
  frontend:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: elizabethbel/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/
      - redoc:/app/api/docs/
  frontend:
    env_file: .env
    image: elizabethbel/foodgram_frontend
    volumes:
      - frontend:/app/build/
  gateway:
    image: elizabethbel/foodgram_gateway
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - redoc:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/media/
      - frontend:/usr/share/nginx/html/
