# Generated by Django 3.2.3 on 2023-10-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='id_sh',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
