# Generated by Django 3.2.3 on 2023-10-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231013_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='id_sh',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
